import random

from flask import Flask, render_template, jsonify

app = Flask(__name__)

# List of questions, each with four options and the correct option index
questions = [
    {'question': 'The specificity of the mythological worldview:', 'options': ['The unity of man and the world', 'Logical representation of the world', 'Believing in one God', 'Reasoning and proving', 'Expressing inner side of the man'], 'answer': 0},
    {'question': 'Philosophical worldview has its own specifics:', 'options': ['based on the logical method of cognition', 'based on the rational level of knowledge', 'has its own set of concepts, categories, special terms.', 'is a system of knowledge', 'all answer', 'are', 'correct'], 'answer': 6},
    {'question': 'The object of philosophy:', 'options': ['the man and society', 'the nature and the god', 'the being and reality', 'the world and the man', 'mind and thinking'], 'answer': 3},
    {'question': 'The subject of philosophy is:', 'options': ['the most general laws and patterns of development and functioning of human society, thinking', 'and  the', 'universe', 'the fundamental principles of being', 'the Arche', 'the man in the world', 'space and time'], 'answer': 2},
    {'question': 'The main divisions of philosophy:', 'options': ['Sociology, culture, myth, religion', 'Physics, psychology, chemistry', 'Science, art, moral, politics', 'Gnoseology, ontology, ethics, aesthetics', 'Worldview, religion, mythology'], 'answer': 4},
    {'question': 'Which function doesn’t belong to philosophy:', 'options': ['Worldview', ',', 'Scientific', 'Ideological', 'Critical', 'Methodological'], 'answer': 3},
    {'question': 'The basic question of philosophy:', 'options': ['What is primary: consciousness or matter?', 'What is primary: egg or hen?', 'What is primary:', 'man', 'or nature?', 'To be or not to be?', 'What is the essence of life?'], 'answer': 0},
    {'question': 'The other side of the basic question of philosophy:', 'options': ['Relation of thinking to being', 'Is there the God?', 'What is the meaning of life?', 'Who created the man?', 'What is reality?'], 'answer': 0},
    {'question': 'Solution of the basic question of philosophy:', 'options': ['Gnosticism and agnosticism', 'Dualism and monism', 'Materialism and idealism', 'Naturalism and sociologism', 'Theism and atheism'], 'answer': 2},
    {'question': 'Solution of the other side of the basic question of philosophy:', 'options': ['Gnosticism and agnosticism', 'Dualism and monism', 'Materialism and idealism', 'Naturalism and sociologism', 'Theism and atheism'], 'answer': 5},
    {'question': 'Metaphysics in philosophy states:', 'options': ['the world is unreal', 'the world is flux', 'the world is static, unchanging', 'the world is real', 'the world is complex'], 'answer': 3},
    {'question': 'Dialectics in philosophy states:', 'options': ['the world is unreal', 'the world is flux', 'the world is static, unchanging', 'the world is real', 'the world is complex'], 'answer': 5},
    {'question': 'Consciousness is state of:', 'options': ['mental', 'perception', 'sensation', 'thinking', 'feeling'], 'answer': 4},
    {'question': 'The central problem of Consciousness:', 'options': ['Ideality', 'Reality', 'Mind and body', 'Truth', 'Qualia'], 'answer': 2},
    {'question': 'What does NOT belong to Sensory knowledge?', 'options': ['sensations', 'perceptions', 'representations', 'reasoning', 'imagination'], 'answer': 3},
    {'question': 'What does NOT belong to Rational knowledge?', 'options': ['concepts', 'judgments', 'conclusions', 'intuition', 'theories'], 'answer': 4},
    {'question': 'True being according to Plato:', 'options': ['atoms', 'ideas', 'things', 'souls', 'god'], 'answer': 1},
    {'question': 'Being according to Aristotle:', 'options': ['substance', 'predicate', 'quality', 'quantity', 'idea'], 'answer': 0},
    {'question': 'Being according to Heidegger:', 'options': ['essence', 'substance', 'existence', 'reality', 'ideality'], 'answer': 2},
    {'question': 'Human according to Social Darwinism is:', 'options': ['symbolic animal', 'organism', 'sentient being', 'moral being', 'social being'], 'answer': 5},
    {'question': 'Human according to Marxism:', 'options': ['symbolic animal', 'organism', 'sentient being', 'moral being', 'social being'], 'answer': 4},
    {'question': 'Human according to Descartes:', 'options': ['symbolic animal', 'organism', 'rational being', 'moral being', 'social being'], 'answer': 2},
    {'question': 'Moral is an object of study of:', 'options': ['axiology', 'epistemology', 'aesthetics', 'ethics', 'logics'], 'answer': 4},
    {'question': '«Things-in itself» by Kant is', 'options': ['Thins we can cognize', 'Things we cannot cognize', 'Things existing', 'Things non-existing', 'Ideal things'], 'answer': 2},
    {'question': '«noumena» by Kant is', 'options': ['Unknowable world', 'Knowable world', 'Reality', 'Sensual images of objects', 'Existence'], 'answer': 1},
    {'question': '«phenomena» by Kant is', 'options': ['W', 'orld', 'Reality', 'Sensual images of objects', 'Essence', 'Existence'], 'answer': 4},
    {'question': 'Tengrism can be defined as:', 'options': ['Monotheism', 'Deism', 'System of beliefs', 'Philosophy', 'Theism'], 'answer': 3},
    {'question': 'Shamanism is a form of:', 'options': ['Spiritualism', 'Totemism', 'Magic', 'Mythology', 'Religion'], 'answer': 9},
    {'question': 'Combination of different Beliefs, Faiths, Thoughts in one Unique Thinking System is called:', 'options': ['Syncretism', 'Natural philosophy', 'Science', 'Mythology', 'Religion'], 'answer': 1},
    {'question': 'Levy-Bruhl explained this quality by saying that the primitive mentality obeys something he called ‘the law of participation’, which means that thoughts can be joined by connections which having nothing in common with those of our logic. What did he mean?:', 'options': ['Animism', 'Totemism', 'Mythology', 'Magic', 'Spiritualism'], 'answer': 3},
    {'question': 'Kazakh nomads had various cults and rites. Which one was essential for Kazakh worldview?:', 'options': ['Cult of ancestors', 'Cult of the Sun', 'Cult of the fire', 'Cult of the earth', 'Cult of the sky'], 'answer': 1},
    {'question': 'What is the name of philosophical system of Marxism?', 'options': ['Objective idealism', 'Subjective idealism', 'Mechanical materialism', 'Dialectical materialism', 'Metaph', 'y', 'sical materialism'], 'answer': 3},
    {'question': 'The central category of Marx’s Historical materialism:', 'options': ['Politics', 'Economics', 'F', 'orms', 'of social consciousness', 'Social-economic formation', 'Industrial relations'], 'answer': 6},
    {'question': 'Freedom in accordance with the teachings of Baruch Spinoza is:', 'options': ['Human will', 'God’s will', 'Human action', 'Recognized necessity', 'Natural law'], 'answer': 3},
    {'question': 'In the irrational philosophy of Soren Kierkegaard, the central problem is:', 'options': ['The essence of man', 'Rational thinking', 'The problem of truth', 'Human existence', 'Knowledge of God'], 'answer': 3},
    {'question': "The ethical ideal of Nietzsche's philosophy is:", 'options': ['Hedonist', 'Christian', 'Muslim', 'Stoick', 'Superman'], 'answer': 4},
    {'question': 'The main philosophical categories of Albert Camus:', 'options': ['Being and thinking', 'Absurdity and rebellion', 'Existence and non-existence', 'Essence and existence', 'Life and death'], 'answer': 1},
    {'question': 'Why does Jean Paul Sartre believe that Existentialism is humanism?', 'options': ['Man is a free creature', 'Man himself determines his existence', 'Man loves', 'Man is a god-like creature', 'Man creates'], 'answer': 1},
    {'question': 'What layer of the human psyche was discovered by Sigmund Freud?', 'options': ['Thinking', 'Unconscious', 'Archetypes', 'Imagination', 'Memory'], 'answer': 1},
    {'question': 'What ancient Greek philosopher believed that the main task was self-knowledge:', 'options': ['Plato', 'Socrates', 'Aristotle', 'Thales', 'Plotinus'], 'answer': 4},
    {'question': 'Translation of word “axiology”:', 'options': ['Study of', 'values.', 'Cosmo centrism.', 'Love Theo', 'Pantheism', 'Love', 'Humanity.'], 'answer': 1},
    {'question': '“There are only two substances in the beginning of the world – thinking and extended substances (dualism) is from philosophy of…', 'options': ['E.Kant', 'D.Hume', 'R.Descartes', 'J.-', 'P.Sartre', 'Protagoras'], 'answer': 2},
    {'question': 'Theory of scientific knowledge is called as…', 'options': ['Cognition', 'Epistemology', 'Social philosophy', 'Feeling', 'Axiology'], 'answer': 2},
    {'question': 'The object of philosophy is:', 'options': ['Cognition process', 'and the place of man in this world', 'World in whole and the place of man in this world.', 'Human being.', 'Truth,', 'unconcealment', '.', 'Mind', 'at whole'], 'answer': 2},
    {'question': 'Ethic is:', 'options': ['A study of nature, origin and limits of human cognition', 'A study of', 'wisdom', 'A', 'study', 'of moral', 'ity', 'and moral', 'behaviour', 'Branch of physics', 'World religion'], 'answer': 9},
    {'question': 'Aesthetics is:', 'options': ['A study of nature, origi', 'n and limits of human cognition', 'A philosophical study of principles, moral and human', 'behavior', 'A', 'study', 'of', 'beauty', 'and art', 'One of the directions of Buddhism', 'Philosophy as a system'], 'answer': 8},
    {'question': 'The first historical type of outlook that is considered as is a system of ancient legends.', 'options': ['P', 'hilosophy', 'Science', 'Ethics', 'Mythology', 'Th', 'eology'], 'answer': 6},
    {'question': 'Faith in the supernatural force(-s), which is based on a strong system of moral norms and the special organization of people, is…', 'options': ['Religion', 'Ontology', 'Physics', 'Epicurianism', 'Substancialism'], 'answer': 2},
    {'question': 'The Socratic ethical rationalism was formulated as', 'options': ['Virtue is religion', 'Virtue is arts', 'Virtue is knowledge', 'Virtue is war', 'Virtue is interests'], 'answer': 2},
    {'question': 'One of the outstanding French existentialist:', 'options': ['David Hume', 'Georg Hegel', 'Albert Camus', 'Francis Bacon', 'Martin Heidegger'], 'answer': 2},
    {'question': 'Division to Subjective spirit, Objective spirit, Absolute spirit comes from philosophy of…?', 'options': ['Fichte', 'Hegel', 'Kant', 'Shelling', 'Marx'], 'answer': 1},
    {'question': 'Ancient eastern philosophy developed mainly in…', 'options': ['India and China', 'India and Japan', 'Persia and China', 'Egypt and China', 'India and Korea'], 'answer': 0},
    {'question': '“Act only on that maxim through which you can at the same time will that become a universal law” is...', 'options': ['the Hegel’s Categorical imperative', 'the Kant’s Categorical imperative', 'the Kant’s Hypothetical imperative', 'the Fichte’s Hypothetical imperative', 'the Hegel’s Hypothetical imperative'], 'answer': 1},
    {'question': 'The famous Descartes’s formula “Cogito, ergo sum” is translated from Latin as', 'options': ['I think, therefore, I have truth', 'I think, therefore, I have power', 'I think, therefore, I have faith', 'I think, therefore, I', 'exist', 'I think, therefore, I have values'], 'answer': 4},
    {'question': 'Universal law in Indian philosophy, which operates in the past, present and future, is called…', 'options': ['Thinking', 'Experience', 'Analysis', 'Induction', 'Karma'], 'answer': 5},
    {'question': 'The first Fr.Baconian idol of all human mind is', 'options': ['Cave', 'Marketplace', 'Tribe', 'Theatre', 'Mind'], 'answer': 2},
    {'question': 'The second Fr.Baconian idol of personal mind is', 'options': ['Cave', 'Marketplace', 'Tribe', 'Theatre', 'Mind'], 'answer': 0},
    {'question': 'The third Fr.Baconian idol of mind referred to using terms and words is', 'options': ['Cave', 'Marketplace', 'Tribe', 'Theatre', 'Mind'], 'answer': 1},
    {'question': 'The fourth Fr. Baconian idol of mind referred to authorities is', 'options': ['Cave', 'Marketplace', 'Tribe', 'Theatre', 'Mind'], 'answer': 3},
    {'question': 'The doctrine about that knowledge is based on experience is:', 'options': ['Empiricism', 'Rationalism', 'Agnosticism', 'Abstract general ideas', 'Complexity'], 'answer': 1},
    {'question': 'E.Kant’s categorical imperative is about…', 'options': ['There’s no place like home.', 'The world is round.', 'Moral problems', '.', 'Everybody everywhere is pretty much the same', '.', 'Physical problems', '.'], 'answer': 3},
    {'question': 'The translation of the word “philosophy”:', 'options': ['Pantheism', 'Love', 'of', 'wisdom.', 'Cosmo centrism.', 'Love Theo', 'Love', 'Human'], 'answer': 3},
    {'question': 'The word “Sophist” is translated from Greek as:', 'options': ['Wise man', 'Warrior', 'Judge', 'Man', 'Thinker'], 'answer': 0},
    {'question': 'He was called «the first teacher»:', 'options': ['Socrates', 'Aristotle', 'Plato', 'Diogenus', 'Heraclitus'], 'answer': 1},
    {'question': 'What beginning (Arche) did Heraclitus recognize?', 'options': ['Logos', '(fire)', 'Virtue', 'Intelligence', 'Honor', 'Pleasure'], 'answer': 1},
    {'question': 'What beginning did Pythagoras recognize?', 'options': ['Numbers', 'D', 'ialectical', 'argument', 'R', 'ational', 'instruction', 'L', 'earning', 'from our mistakes', 'B', 'reathing'], 'answer': 0},
    {'question': 'A teaching of Aristotle is called as…', 'options': ['Academicism', 'Peripatetism', 'Buddhism', 'Atheism', 'Pantheism'], 'answer': 1},
    {'question': 'Under the Renaissance human was considered to be as', 'options': ['Man', 'is a', 'political creature.', 'Man', 'is a', 'thinking being.', 'Man', 'is a', 'religious', 'being', '.', 'Hum', 'an', 'is a', 'creator, artist', ',', 'en', 'rich', 'ed', 'microcosm', '.', 'Man', 'is a', 'sin', 'n', 'er', '.'], 'answer': 21},
    {'question': '“I know that I know nothing” was proclaimed by…', 'options': ['Thales', 'Pythagorus', 'Democritus', 'Seneka', 'Socrates'], 'answer': 4},
    {'question': 'A thinker who formulated 5 proofs of existence of God:', 'options': ['Augustine', 'Erasmus of Rotterdam.', 'Thomas Aquinas.', 'Machiavelli', 'Abelyar'], 'answer': 2},
    {'question': 'Myth of the Cave was developed by:', 'options': ['Augustine', 'Erasmus of Rotterdam', 'Plato', 'Makiavelli', 'Abelyar'], 'answer': 3},
    {'question': 'Theocentrism provides that in the center of the universe is…', 'options': ['God', 'Something mystical', 'Poetics', 'Human', 'Science'], 'answer': 1},
    {'question': 'Defining characteristic of the religious outlook is:', 'options': ['Belief in', 'art of superstitions', 'Belief in contemptuous attitude to science, the denial of their validity', 'Belief in wisdom', 'Belief in the supernatural, otherworldly forces, having the opportunity to influence the', 'course of world events', 'Belief in d', 'enial of human freedom, the belief that all actions originally defined by God'], 'answer': 7},
    {'question': 'One of the main characteristics of the Renaissance is:', 'options': ['Atheism', 'Theologism', 'Sociocentrism', 'Cosmocentrism', 'Anthropocentrism'], 'answer': 4},
    {'question': 'Creationism is the idea that the world and mankind created by…', 'options': ['God', 'Something mystical', 'Poetics', 'Human', 'Science'], 'answer': 1},
    {'question': 'Searching human individuality is the specific feature of Philosophy of...', 'options': ['Conventialism', 'Life', 'Existentialism', 'Rationalism', 'Conformism'], 'answer': 2},
    {'question': 'The idea that destinies of the world and people are determined by God is…', 'options': ['Freedom', 'Desire', 'Canon', 'Providentialism', 'Emotions'], 'answer': 3},
    {'question': 'Who offered psychoanalytic theory in human nature?', 'options': ['Leonardo da Vinci', 'Nikolas of Cusa', 'L', 'oranzo', 'Valla', 'Tomaso', 'Campanella', 'Sigmund Freud'], 'answer': 7},
    {'question': '“Thus Spoke Zarathustra” is a work of …', 'options': ['R.Descartes', 'F.Nietzsche', 'Albert Camus', 'Karl Marx', 'Martin Heidegger'], 'answer': 1},
    {'question': 'Branch of philosophy that studies historical knowledge and interpretation of historical process:', 'options': ['Philosophy of history', 'Logics', 'Ontology', 'History of philosophy', 'Epistemology'], 'answer': 0},
    {'question': 'The definition of social economic formation in materialism was first developed by...', 'options': ['Engels', 'Stalin', 'Marx', 'Rousseau', 'Lenin'], 'answer': 3},
    {'question': 'Who is the author of the books “Either/or”, “Fear and Trembling”?', 'options': ['Rousseau', 'Lenin', 'Kierkegaard', 'Marx', 'Sartre'], 'answer': 2},
    {'question': 'Who indicated the difference between conscious and unconscious in human mind?', 'options': ['Plato', 'Freud', 'Hume', 'Marx', 'Sartre'], 'answer': 1},
    {'question': 'Aesthetical values are:', 'options': ['Love, friendship', 'Beauty, art, harmony, style', 'Civil rights', 'Freedom of word and personality', 'Social justice'], 'answer': 1},
    {'question': '“God is dead” said...', 'options': ['F.Nietzsche', 'Heraclitus', 'Plato', 'E.Kant', 'F.Hegel'], 'answer': 0},
    {'question': 'What are the main founders of philosophy of existentialism:', 'options': ['Camus, Freud,', 'Florensky', 'Camus, Sartre, Kierkegaard', 'Sartre, Spengler, Schelling', 'B.Russel', '.', 'I.Kant, Freud, Florensky', 'Russel, Popper, Adler'], 'answer': 2},
    {'question': '«The man of absurd» according to Albert Camus is one who understands:', 'options': ['Essence of life', 'Meaning of life', 'Meaningless of existence', 'Philosophy', 'Others'], 'answer': 2},
    {'question': '«The man of rebellion» according to Albert Camus is one who states:', 'options': ['I think, therefore I exist', 'I rebel, therefore I exist', 'I', 'doubt', ', therefore I exist', 'I', 'agree', ', therefore I exist', 'I', 'argue', ', therefore I exist'], 'answer': 1},
    {'question': '«Borderline situations» according to Sartre is the situation when a man becomes aware of:', 'options': ['Purpose', 'of his life', 'Problems', 'Conflicts', 'The meaning of his', 'life', 'His coming death'], 'answer': 6},
    {'question': 'According to Sartre: man is:', 'options': ['A p', 'roject of himself', 'A social animal', 'Microcosmos', 'Symbolic animal', 'God’s project'], 'answer': 1},
    {'question': 'According to Sigmund Freud «Neurotic» is:', 'options': ['A crazy man', 'A healthy person with neurotic symptoms', 'A schizophrenic', 'person', 'An anxious man', 'A s', 'ick person'], 'answer': 1},
    {'question': 'According to Sigmund Freud «The Unconscious» is:', 'options': ['Ego', 'Super Ego', 'Id', 'Othe', 'r', 'Ego', 'Animus'], 'answer': 3},
    {'question': 'According to Carl Gustav Jung «Archetypes» are:', 'options': ['Symbols of Individual Unconscious', 'Dreams', 'Symbols of Collective Unconscious', 'Myths', 'Spirits'], 'answer': 2},
    {'question': 'According to Carl Gustav Jung human behavior is determined by:', 'options': ['Individual unconsciousness', 'Environment', 'Education', 'Parents', 'Collective unco', 'nsciousness'], 'answer': 6},
    {'question': 'According to Sigmund Freud human behavior is determined by three authorities:', 'options': ['Mind, will, desire', 'Ego, Id, Super Ego', 'Body, mind, soul', 'Father, mother, teacher', 'Nanny, teacher, boss'], 'answer': 1},
    {'question': 'According to S. Kierkegaard the main problem of philosophy is:', 'options': ['Human essence', 'Human existence', 'Human', 'origin', 'Human', 'mind', 'Human', 'body'], 'answer': 1},
    {'question': 'S. Kierkegaard wanted to understand why:', 'options': ['Man', 'is', 'an animal', 'Man', 'is social', 'Man was thrown into the world', 'Man', 'is', 'evil', 'Man', 'is kind'], 'answer': 5},
    {'question': 'According to F. Nietzsche human manifests themselves in:', 'options': ['Will to die', 'Will to live', 'Will to power', 'Will to kill', 'Will to know'], 'answer': 2},
    {'question': 'According to F. Nietzsche, Superman is a person who:', 'options': ['Does not like people', 'Does', 'n', 'ot suffer', 'Does not like moral', 'Does not die', 'Does not believe in God'], 'answer': 6},
    {'question': 'Which ones are the typical Kazakh mythological forms?', 'options': ['Totemism and animism', 'Tengrism and shamanism', 'Magic and spiritualism', 'Polytheism and paganism', 'Pantheism and fetishism'], 'answer': 1},
    {'question': 'Philosophy of Marxism is called:', 'options': ['Metaphysical materialism', 'Dialectical materialism', 'Historical materialism', 'Objective idealism', 'Subjective materialism'], 'answer': 1},
    {'question': 'Socio-political theory of Marxism is called:', 'options': ['Metaphysical materialism', 'Dialectical materialism', 'Historical materialism', 'Objective idealism', 'Subjective materialism'], 'answer': 2},
    {'question': 'Philosophical method of Marxism is called:', 'options': ['Metaphysics', 'Dialectics', 'Deduction', 'Induction', 'Analogy'], 'answer': 1},
    {'question': 'The idea of Communism in Marxism represents:', 'options': ['Class society', 'Classless society', 'Perfect society', 'Free society', 'Rich society'], 'answer': 1},
    {'question': 'Historical type of societies in Marxism is called:', 'options': ['Basis and superstructure', 'Social economic formation', 'Class society', 'Classless society', 'Ideal society'], 'answer': 1},
    {'question': 'What is Consciousness?', 'options': ['function of brain', 'reflection of reality', 'self-awareness', 'ideality', 'all of them'], 'answer': 4},
    {'question': 'Elements of Consciousness according to A. G. Spirkin:', 'options': ['sensual', 'rational', 'value', 'motivation', 'all of them'], 'answer': 4},
    {'question': 'Which property of consciousness describes the immaterial essence of consciousness?', 'options': ['ideality', 'intentionality', 'ideationality', 'reflection', 'self-awareness'], 'answer': 0},
    {'question': 'who is Homo Sapiens?', 'options': ['Man with thinking', 'Man with feelings', 'Man with', 'hands', 'Man', 'with eyes', 'Man with', 'soul'], 'answer': 0},
    {'question': 'consciousness according to theory of Dualism:', 'options': ['material substance', 'ideationality', 'immaterial substance', 'reflection', 'self-awareness'], 'answer': 2},
    {'question': 'consciousness according to theory of Darwinism', 'options': ['property of man', 'idea', 'l property', 'reflection', 'of man', 'self-awareness', 'highest', 'property of brain'], 'answer': 7},
    {'question': 'consciousness according to theory of Logical behaviorism', 'options': ['thoughts', 'speech', 'acts', 'instincts', 'awareness'], 'answer': 2},
    {'question': 'Self-consciousness is the characteristic of consciousness which describes:', 'options': ['intentionality', 'ideationality', 'reflection', 'ideality', 'self-awareness'], 'answer': 4},
    {'question': 'Language is:', 'options': ['outer side of consciousness', 'inner side of', 'consciousness', 'all ideas', 'reflective organ', 'self-awareness'], 'answer': 0},
    {'question': 'What is Ontology?', 'options': ['study of mind', 's', 'tudy of Being', 'study of nature', 'study of', 'god', 'a', 'study', 'of man'], 'answer': 2},
    {'question': 'What the term «metaphysics» means?', 'options': ['Something real', 'what comes after physics', 'something unreal', 'unnowable', 'knowable'], 'answer': 1},
    {'question': 'What is Being?', 'options': ['real', 'category for existence', 'spiritual', 'mental', 'related to human', 's'], 'answer': 1},
    {'question': 'What is the problem of Being?', 'options': ['What is world', 'what is the essence of the world', 'what is reality', 'what is the god', 'what is the mind'], 'answer': 1},
    {'question': 'What is Substance?', 'options': ['matter', 'independent entity', 'spirit', 'predicates of things', 'essence of things'], 'answer': 1},
    {'question': 'Who said: «Being is, but there is not non-being»', 'options': ['Socrates', 'Parmenides', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 2},
    {'question': 'Who said: «If something denotes the essence of a thing, then it makes sense that being for it does not lie in something else»', 'options': ['Socrates', 'Parmenides', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 3},
    {'question': 'Who said: «Being is One»', 'options': ['Socrates', 'Parmenides', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 2},
    {'question': 'Who said: «Being is God»', 'options': ['Socrates', 'Christianity', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 5},
    {'question': 'Who said: «Being is Two»', 'options': ['Socrates', 'Descartes', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 2},
    {'question': 'Who said: «Being is plural»', 'options': ['Socrates', 'Leibniz', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 2},
    {'question': 'Who said: «Being is Absolute Idea»', 'options': ['Socrates', 'Hegel', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 2},
    {'question': 'Who said: «Being is Man»', 'options': ['Socrates', 'Heidegger', 'Aristotle', 'Plato', 'Plotinus'], 'answer': 2},
    {'question': 'Forms of Being', 'options': ['Natural', 'All of them', 'Spiritual', 'Human', 'Social'], 'answer': 1},
    {'question': 'what is Matter?', 'options': ['Ideal being', 'material being', 'spiritual being', 'divine being', 'social being'], 'answer': 1},
    {'question': 'Attributes of Matter:', 'options': ['movement', 'All of them', 'time', 'space', 'reflection'], 'answer': 1},
    {'question': 'Forms of Motion:', 'options': ['physical', 'all of them', 'chemical', 'biological', 'social'], 'answer': 1},
    {'question': 'What is Development?', 'options': ['Motion from down to up', 'motion from simple to complex', 'motion  from', 'low to high', 'motion from left to right', 'motion from up to down'], 'answer': 1},
    {'question': 'Two concepts of Development:', 'options': ['Regress and progress', 'methaphysical', 'and dialectical', 'cyclic and linear', 'eternal return', 'stagnation and change'], 'answer': 2},
    {'question': 'types of space:', 'options': ['wide', 'Three-dimensional', 'narrow', 'virtual', 'cosmos'], 'answer': 1},
    {'question': 'types of time:', 'options': ['physical', 'all of them', 'psychological', 'biological', 'social'], 'answer': 1},
    {'question': 'Philosophical category which describes visible and invisible sides of things:', 'options': ['Content and form', 'Essence and phenomenon', 'Cause and effect', 'Necessity and contingency', 'Possibility and reality'], 'answer': 1},
    {'question': 'Philosophical category which describes inner and outer side of things:', 'options': ['Content and form', 'Essence and phenomenon', 'Cause and effect', 'Necessity and contingency', 'Possibility and reality'], 'answer': 0},
    {'question': 'Philosophical category which describes determinism:', 'options': ['Content and form', 'Essence and phenomenon', 'Cause and effect', 'Necessity and contingency', 'Possibility and reality'], 'answer': 2},
    {'question': 'What is cognition?', 'options': ['Thinking', 'abt', 'smth', 'mastering knowledge', 'working on book', 'imagining o', 'f', 'smth', 'awareness', 'of', 'smth'], 'answer': 4},
    {'question': 'What is knowledge?', 'options': ['books', 'information', 'traditions', 'customs', 'opinion'], 'answer': 2},
    {'question': 'What is common between Knowledge and Cognition?', 'options': ['They are the same', 'knowledge is the result of cognitive process', 'they are different', 'both are process', 'cognition needs prior knowledge'], 'answer': 1},
    {'question': 'What is Epistemology?', 'options': ['Theory of knowledge', 'theory', 's', 'cientific knowledge', 'theory of', 'technology', 'theory of', 'methods', 'theory of', 'philosophical knowledge'], 'answer': 0},
    {'question': 'What is Gnoseology?', 'options': ['Theory of knowledge', 'theory scientific knowledge', 'theory of technology', 'theory of methods', 'theory of philosophical knowledge'], 'answer': 0},
    {'question': 'What is Gnosticism?', 'options': ['Cognitive pessimism', 'cognitive optimism', 'cognitive disbelief', 'cognitive doubts', 'cognitive negation'], 'answer': 4},
    {'question': 'What is Agnosticism?', 'options': ['Cognitive pessimism', 'cognitive optimism', 'cognitive disbelief', 'cognitive doubts', 'cognitive negation'], 'answer': 5},
    {'question': 'What is Skepticism?', 'options': ['Cognitive pessimism', 'cognitive optimism', 'cognitive disbelief', 'cognitive doubts', 'cognitive negation'], 'answer': 4},
    {'question': 'Which ideas are TRUE according to Descartes «Theory of Ideas»?', 'options': ['Mind ideas', 'innate ideas', 'sensory ideas', 'authorities’ ideas', 'common sense'], 'answer': 1},
    {'question': 'Who believed that TRUTH can be proved in the process of socio-historical practice?', 'options': ['Hegel', 'Marx', 'Kant', 'Bacon', 'Lock'], 'answer': 2},
    {'question': 'Who believed that we can cognize only Phenomena?', 'options': ['Hegel', 'Marx', 'Kant', 'Bacon', 'Lock'], 'answer': 3},
    {'question': 'Type of Cognition based on Conceptual understanding the reality:', 'options': ['ordinary', 'cogniton', 'scientific cognition', 'practical cognition', 'artistic cognition', 'moral cognition'], 'answer': 2},
    {'question': 'Levels of Cognition:', 'options': ['Ordinary and theoretical', 'sensual', 'and rational', 'basic and complex', 'lower and higher', 'everyday', 'and', 'scentisfic'], 'answer': 2},
    {'question': 'What is Judgment?', 'options': ['Statement reflecting the things and their properties', 'logical image that reproduces the essential properties of objects', 'deduction from several interrelated judgments of a new judgment', 'comprehend the truth by seeing it clear', 'integral image of an object in the unity reflected through sensations.'], 'answer': 0},
    {'question': 'What is Concept?', 'options': ['Statement reflecting the things and their properties', 'logical image that reproduces the essential properties of objects', 'deduction from several interrelated judgments of a new judgment', 'comprehend the truth by seeing it clear', 'integral image of an object in the unity reflected through sensations.'], 'answer': 1},
    {'question': 'What is Inference?', 'options': ['Statement reflecting the things and their properties', 'logical image that reproduces the essential properties of objects', 'deduction from several interrelated judgments of a new judgment', 'comprehend the truth by seeing it clear', 'integral image of an object in the unity reflected through sensations.'], 'answer': 3},
    {'question': 'What is Intuition?', 'options': ['Statement reflecting the things and their properties', 'logical image that reproduces the essential properties of objects', 'deduction from several interrelated judgments of a new judgment', 'comprehend the truth by seeing it clear', 'integral image of an object in the unity reflected through sensations.'], 'answer': 3},
    {'question': 'What is Truth in Classical sense?', 'options': ['', 'Truth is the correspondence of knowledge to', 'reality;', 'this is what is confirmed by', 'experience;', 'is a kind of agreement – a', 'convention;', 'usefulness of the knowledge', 'gained;', 'effectiveness of its use in practice.'], 'answer': 3},
    {'question': 'What is correct about Fallacy?', 'options': ['Deliberate distortion of truth', 'is the essential part of the cognitive process', 'Lie', 'Is the', 'fail', 'of cognitive process', 'Ideological essence of cognition'], 'answer': 0},
    {'question': 'Axiology studies:', 'options': ['notions', 'values', 'norms', 'taboos', 'laws'], 'answer': 1},
    {'question': 'Absolute values:', 'options': ['yin', '-', 'yang', 'truth, beauty, good', 'justice, injustice', 'God', 'Human health'], 'answer': 3},
    {'question': 'Classification of values by carrier:', 'options': ['material, spiritual', 'individual, supra individual', 'economical', ', political', 'social, family', 'absolute,', 'specific'], 'answer': 1},
    {'question': 'Classification of values by existence:', 'options': ['material, spiritual', 'individual, supra individual', 'economical', ', political', 'social, family', 'absolute, specific'], 'answer': 0},
    {'question': 'What is Ethics?', 'options': ['theory of art', 'theory of morality', 'theory of society', 'theory of religion', 'theory of nature'], 'answer': 1},
    {'question': 'What is Morality?', 'options': ['social regulation form through beauty-ugly', 'social regulation form through', 'good', '-', 'bad', 'social regulation form through justice-injustice', 'social regulation form through useful-useless', 'social regulation form through faith-', 'denial'], 'answer': 4},
    {'question': 'Why is Ethics practical science?', 'options': ['It is studied to know what is good', 'it is studied', 'in order to', 'become virtuous', 'It is studied to learn what is evil', 'It is studied to know more', 'It is studied to get wisdom'], 'answer': 4},
    {'question': 'Difference between Morality and Mores?', 'options': ['No difference', 'difference between what is Due and what is Real', 'norms and ideals', 'good and bad', 'week and strong'], 'answer': 1},
    {'question': 'Main Christian values:', 'options': ['Pride and humility', 'faith, hope, love', 'cupidity and', 'generocity', 'list and chastity', 'true and lie'], 'answer': 1},
    {'question': 'Which one is Stoic principle?', 'options': ['live for pleasure and well-being', 'focus on what you control', 'live a complete and fulfilling life', 'usefulness,', 'practicabilty', ', benefit', 'prudence, courage, justice'], 'answer': 1},
    {'question': 'Which one is Hedonistic principle?', 'options': ['live for pleasure and well-being', 'focus on what you control', 'live a complete and fulfilling life', 'usefulness,', 'practicabilty', ', benefit', 'prudence, courage, justice'], 'answer': 0},
    {'question': 'Which one is Pragmatic principle?', 'options': ['live for pleasure and well-being', 'focus on what you control', 'live a complete and fulfilling life', 'usefulness,', 'practicabilty', ', benefit', 'prudence, courage, justice'], 'answer': 5},
    {'question': 'What is Epicureanism principle?', 'options': ['live for pleasure and well-being', 'focus on what you control', 'live a complete and fulfilling life', 'usefulness,', 'practicabilty', ', benefit', 'prudence, courage, justice'], 'answer': 0},
    {'question': 'What is Eudemonism principle?', 'options': ['live for pleasure and well-being', 'focus on what you control', 'live a complete and fulfilling life', 'usefulness,', 'practicabilty', ', benefit', 'prudence, courage, justice'], 'answer': 2},
    {'question': 'Essence of Art in classical sense:', 'options': ['Art is representation of reality', 'Art is beauty, truth, good', 'Art is expression of spiritual world of artist', 'Art is only fine art', 'Art is skill and mastery'], 'answer': 1},
    {'question': 'Essence of Art in Renaissance sense', 'options': ['Art is representation of reality', 'Art is beauty, truth, good', 'Art is expression of spiritual world of artist', 'Art is only fine art', 'Art is skill and mastery'], 'answer': 0},
    {'question': 'Essence of Art in 17-18 centuries:', 'options': ['Art is representation of reality', 'Art is beauty, truth, good', 'Art is expression of spiritual world of artist', 'Art is only fine art', 'Art is skill and mastery'], 'answer': 1},
    {'question': 'Essence of Art in contemporary sense:', 'options': ['Art is representation of reality', 'Art is beauty, truth, good', 'Art is expression of spiritual world of artist', 'Art is only fine art', 'Art is skill and mastery'], 'answer': 2},
    {'question': 'Essence of Art in traditional sense:', 'options': ['Art is representation of reality', 'Art is beauty, truth, good', 'Art is expression of spiritual world of artist', 'Art is only fine art', 'Art is skill and mastery'], 'answer': 0},
    {'question': 'Aesthetic categories of Nietzsche:', 'options': ['sublimation', 'Apollonian and Dionysian', 'absurd', 'mimesis', 'catharsis'], 'answer': 1},
    {'question': 'Aesthetic categories of Freud:', 'options': ['sublimation', 'Apollonian and Dionysian', 'absurd', 'mimesis', 'catharsis'], 'answer': 0},
    {'question': 'Aesthetic categories of Existentialism:', 'options': ['sublimation', 'Apollonian and Dionysian', 'absurd', 'mimesis', 'catharsis'], 'answer': 2},
    {'question': 'Aesthetic categories of Plato', 'options': ['sublimation', 'Apollonian and Dionysian', 'absurd', 'mimesis', 'catharsis'], 'answer': 4},
    {'question': 'Aesthetic categories of Aristotle', 'options': ['sublimation', 'Apollonian and Dionysian', 'absurd', 'mimesis', 'catharsis'], 'answer': 5},
    {'question': 'Whose statement is this? – People are born free or slaves.', 'options': ['Erasmus', 'Aristotle', 'Spinoza', 'Rousseau', 'Fromm'], 'answer': 1},
    {'question': 'Whose statement is this? – Freedom is human illusion.', 'options': ['Erasmus', 'Aristotle', 'Spinoza', 'Rousseau', 'Fromm'], 'answer': 3},
    {'question': 'Whose statement is this? – Freedom is realized necessity.', 'options': ['Erasmus', 'Aristotle', 'Spinoza', 'Rousseau', 'Fromm'], 'answer': 3},
    {'question': 'Whose statement is this? – Freedom is democracy and equality.', 'options': ['Erasmus', 'Aristotle', 'Spinoza', 'Rousseau', 'Fromm'], 'answer': 3},
    {'question': 'Whose statement is this? – There is freedom from and freedom for.', 'options': ['Erasmus', 'Aristotle', 'Spinoza', 'Rousseau', 'Fromm'], 'answer': 4},
    {'question': 'Which one describes inevitable course of things which are unavoidable:', 'options': ['liberalism', 'fatalism', 'determinism', 'voluntarism', 'providentialism'], 'answer': 1},
    {'question': 'Which one describes individual, civil rights, free enterprise', 'options': ['liberalism', 'fatalism', 'determinism', 'voluntarism', 'providentialism'], 'answer': 0},
    {'question': 'Which one describes that everything happens due to the objective laws', 'options': ['liberalism', 'fatalism', 'determinism', 'voluntarism', 'providentialism'], 'answer': 2},
    {'question': 'Which one describes that everything happens due to somebody’s will', 'options': ['liberalism', 'fatalism', 'determinism', 'voluntarism', 'providentialism'], 'answer': 3},
    {'question': 'Which one describes the everything happens due to God’s will', 'options': ['liberalism', 'fatalism', 'determinism', 'voluntarism', 'providentialism'], 'answer': 4},
    {'question': 'Tick the criteria of society:', 'options': ['territory', 'all of them', 'self-regulation', 'self-control', 'integrity'], 'answer': 1},
    {'question': 'What is society?', 'options': ['Aggregate of individuals', 'Social system', 'community', 'social relations', 'social groups'], 'answer': 0},
    {'question': 'Which definition of society is of Social Darwinism?', 'options': ['Society is', 'social relations', 'society is organism', 'Society is', 'geographic adaptation', 'Society is', 'ideal place', 'Society is', 'summation of individuals'], 'answer': 2},
    {'question': 'Which definition of society is of Marxism?', 'options': ['Society is social relations', 'society is organism', 'Society is geographic adaptation', 'Society is ideal place', 'Society is summation of individuals'], 'answer': 0},
    {'question': 'Which definition of society is of Naturalism?', 'options': ['Society is social relations', 'society is organism', 'Society is geographic adaptation', 'Society is ideal place', 'Society is summation of individuals'], 'answer': 1},
    {'question': 'Which definition of society is of Utopian?', 'options': ['Society is social relations', 'society is organism', 'Society is geographic adaptation', 'Society is ideal place', 'Society is summation of individuals'], 'answer': 3},
    {'question': 'Which definition of society is of Atomism?', 'options': ['Society is social relations', 'society is organism', 'Society is geographic adaptation', 'Society is ideal place', 'Society is summation of individuals'], 'answer': 4},
    {'question': 'Which one is concise definition of Culture?', 'options': ['Scope of arts', 'is material and spiritual environment created by man', 'life style', 'fine manners', 'customs and traditions'], 'answer': 1},
    {'question': 'What are the main characteristics of a Mass Man according to Ortega y Gasset?', 'options': ['responsibility', 'consumerism', 'education', 'high standards', 'hard', 'work'], 'answer': 1},
]

random.shuffle(questions) # ======
# Index of the current question
question_index = 0

@app.route('/')
def index():
    global question_index
    question = questions[question_index]
    return render_template('index.html', question=question)

@app.route('/next', methods=['POST'])
def next_question():
    global question_index
    # Check if it's the last question, then reset to 0
    if question_index < len(questions) - 1:
        question_index += 1
    else:
        question_index = 0  # Reset to the first question
    return jsonify({'question': questions[question_index]},)

if __name__ == '__main__':
    # app.run(debug=True)
    app.run(host="0.0.0.0", port=5000)

